name: fastapi-mysql

services:
  db-mysql:
    image: mysql
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: alumnosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"