name: fastapi-alumnos

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-alumnos
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - fastapi-db
  fastapi-db:
    image: mysql
    container_name: fastapi-db-alumnos
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: alumnosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"